# Generated by Django 5.0.1 on 2024-02-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offereditem',
            name='date_offered_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
