# Generated by Django 5.0.1 on 2024-02-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='winner',
            old_name='item_id',
            new_name='item',
        ),
    ]
