# Generated by Django 5.0.1 on 2024-02-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_rename_item_id_vote_item_rename_item_id_winner_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='won_on',
        ),
    ]
